version: '3.8'
services:

  # imagem bnews
  bnews:
    build:
      args:
        user: tss
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bnews-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - netbnews

  #nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - netbnews

  # bnewsdb
  bnewsdb:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql #Database will be saved in this folder... DON'T FORGET to add it in .gitignore
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - netbnews

networks:
  netbnews:
    driver: bridge